#ifndef AUZIO_PLATFORM_H
#include "auzio.h"

struct EditorMemory {
    u64 permanent_memory_size;
    void *permanent_memory;

    u64 scratch_memory_size;
    void *scratch_memory;

    b32 is_initialized;
};

enum EditorScanKeyCode {
    EDITOR_SCAN_KEY_UNKNOWN,

    // Letters
    EDITOR_SCAN_KEY_A,
    EDITOR_SCAN_KEY_B,
    EDITOR_SCAN_KEY_C,
    EDITOR_SCAN_KEY_D,
    EDITOR_SCAN_KEY_E,
    EDITOR_SCAN_KEY_F,
    EDITOR_SCAN_KEY_G,
    EDITOR_SCAN_KEY_H,
    EDITOR_SCAN_KEY_I,
    EDITOR_SCAN_KEY_J,
    EDITOR_SCAN_KEY_K,
    EDITOR_SCAN_KEY_L,
    EDITOR_SCAN_KEY_M,
    EDITOR_SCAN_KEY_N,
    EDITOR_SCAN_KEY_O,
    EDITOR_SCAN_KEY_P,
    EDITOR_SCAN_KEY_Q,
    EDITOR_SCAN_KEY_R,
    EDITOR_SCAN_KEY_S,
    EDITOR_SCAN_KEY_T,
    EDITOR_SCAN_KEY_U,
    EDITOR_SCAN_KEY_V,
    EDITOR_SCAN_KEY_W,
    EDITOR_SCAN_KEY_X,
    EDITOR_SCAN_KEY_Y,
    EDITOR_SCAN_KEY_Z,

    // Numbers
    EDITOR_SCAN_KEY_0,
    EDITOR_SCAN_KEY_1,
    EDITOR_SCAN_KEY_2,
    EDITOR_SCAN_KEY_3,
    EDITOR_SCAN_KEY_4,
    EDITOR_SCAN_KEY_5,
    EDITOR_SCAN_KEY_6,
    EDITOR_SCAN_KEY_7,
    EDITOR_SCAN_KEY_8,
    EDITOR_SCAN_KEY_9,

    // Function keys
    EDITOR_SCAN_KEY_F1,
    EDITOR_SCAN_KEY_F2,
    EDITOR_SCAN_KEY_F3,
    EDITOR_SCAN_KEY_F4,
    EDITOR_SCAN_KEY_F5,
    EDITOR_SCAN_KEY_F6,
    EDITOR_SCAN_KEY_F7,
    EDITOR_SCAN_KEY_F8,
    EDITOR_SCAN_KEY_F9,
    EDITOR_SCAN_KEY_F10,
    EDITOR_SCAN_KEY_F11,
    EDITOR_SCAN_KEY_F12,

    // Modifiers
    EDITOR_SCAN_KEY_LEFT_SHIFT,
    EDITOR_SCAN_KEY_RIGHT_SHIFT,
    EDITOR_SCAN_KEY_LEFT_CONTROL,
    EDITOR_SCAN_KEY_RIGHT_CONTROL,
    EDITOR_SCAN_KEY_LEFT_ALT,
    EDITOR_SCAN_KEY_RIGHT_ALT,
    EDITOR_SCAN_KEY_CAPS_LOCK,

    // Common
    EDITOR_SCAN_KEY_ESCAPE,
    EDITOR_SCAN_KEY_BACKSPACE,
    EDITOR_SCAN_KEY_DELETE,
    EDITOR_SCAN_KEY_ENTER,
    EDITOR_SCAN_KEY_TAB,
    EDITOR_SCAN_KEY_SPACE,

    // Navigation
    EDITOR_SCAN_KEY_LEFT,
    EDITOR_SCAN_KEY_RIGHT,
    EDITOR_SCAN_KEY_UP,
    EDITOR_SCAN_KEY_DOWN,
    EDITOR_SCAN_KEY_HOME,
    EDITOR_SCAN_KEY_END,
    EDITOR_SCAN_KEY_PAGE_UP,
    EDITOR_SCAN_KEY_PAGE_DOWN,
    EDITOR_SCAN_KEY_INSERT,

    EDITOR_SCAN_KEY_COUNT
};

#define AUZIO_PLATFORM_H
#endif
